### ISSUE TITLE
Clarifications on the "state of the field"

### ISSUE THREAD

**Issue by akaptano** [FlowModelingControl/flowtorch#24]
In the paper, please clarify how this software compares to other post-processing packages. To my knowledge, there is no mention of similar software packages. For instance, the VisIt package (https://visit-dav.github.io/visit-website/index.html) also supports vtk, hdf5, and netcdf file formats and fluid-flow visualizations. Other examples include Paraview and TecPlot. Please cite and compare with these existing tools. I think this will be a favorable comparison because personally I find VisIt and these other tools excruciating to use.

**Comment by AndreWeiner** [comment]
Hi Alan,

this is indeed an important point, and admit to having missed it when checking the JOSS review criteria. I added the following paragraph in the *statement of need section*:

Besides the subpackages already available in `flowTorch`, the library also integrates nicely with related software packages like [ParaView](https://www.paraview.org/) or [VisIt](https://visit-dav.github.io/visit-website/index.html) for mesh-based post-processing as well as specialized analysis and modeling packages like PyDMD [@demo2018], PySINDy [@desilva2020], or [modred](https://github.com/belson17/modred). Rather than re-implementing functionality already existing in other established libraries, `flowTorch` wraps around them to simplify their usage and streamline the overall post-processing pipeline. For example, we use ParaView's [vtk](https://pypi.org/project/vtk/) package to access various types of VTK files in Python. Gathering point coordinates, write times, or snapshots from several VTK files requires very different steps than when dealing with OpenFOAM or DaVis data.  However, due to the common interface to data sources in `flowTorch`, these tasks appear to be exactly the same for the user. In contrast to `flowTorch`, PyDMD offers a wide range of DMD variants but does not provide access to data. If an advanced DMD algorithm is required, our library can be used to access and pre-process a dataset, before PyDMD is used to perform the modal decomposition.

I push and re-compile the article once I finished including the remaining changes according to issue #25. If you are OK with this paragraph, feel free to close this issue.

Thanks,
Andre

**Comment by akaptano** [comment]
Looks, good. I might also add a sentence noting that your code is much simpler to use (the learning curve is much lower) than ParaView or VisIt (the VisIt manual is like 400 pages if I remember correctly, and the GUI is pretty buggy). 

Best,
Alan
