### ISSUE TITLE
Minor edits in the paper.md file

### ISSUE THREAD

**Issue by akaptano** [FlowModelingControl/flowtorch#25]
First of all, the paper is well-written, flows well, and clearly states the purpose of the software. Great job. 

Some minor edits I'm combining into a single issue:

1. The DaVis file format is mentioned in the abstract, but not defined in the remainder of the paper. It might be good to include this with the discussion in paragraph 1 of the Statement of need Section. 

2. Clarify in paragraph 1 what is meant by "to improve complex technical application". This is pretty vague. For instance, you could improve this by saying something like "to improve the control of industrial processes..." 

3. Clarify in paragraph 1 why "gaining insights from the data is becoming increasingly challenging." Is this simply because of the size of the data? If so, you could combine this sentence with the next one, saying something like "As modern datasets continue to grow, post-processing pipelines will be increasingly important for synthesizing different data formats  and facilitating complex data analysis."

4. The sentence "When confronted with such ideas..." sounds awkward, I recommend changing it to something like "Often these obstacles require significant research time to be spent accessing, converting, ..."

5. Third paragraph in the Statement of Need section: It would be good to define/give examples for "computing statistics, performing modal analysis, or building reduced-order models".  It would be even better to add some references about these things.

6. I think Figure 1 could be improved in a few ways. For instance, it would be good if all the package dependencies were all the same color, to indicate they are the same type of thing. It might be nice to expand this figure, showing some of the sub-libraries like the DMD class, the FileReaders, etc. but this might be too much. 

7. Before the "DMD analysis of airfoil surface data" section, you say "Reduced-order-model (ROM)" but reduced order models have been introduced earlier in the document. It would be good to move the (ROM) abbreviation to the earliest use.

8.  If there is a reference for the airfoil dataset, please add it. 

9. Figure 2: 
    (a) Please clarify if the images are in the (x, z) space, and m. 8, m. 6, etc. refer to modes 8, modes 6, and so on. 
    (b) Other than the shock front, is there some physical interpretations of the DMD modes or their characteristic frequencies (for instance, the top and bottom modes seem to be harmonics)? 
    (c) Please reduce the number of significant digits shown on the colorbars, and it might be good to use the same colorbar for all three modes. 
    (d) Maybe I missed it, but what is the significant of the "cp" in the title? 

10. In the first paragraph of "CNM of the flow past a circular cylinder" Section, it should be "always consultants of three step**s**". It would also be good to add some description and a reference on reduced order models of the cylinder flow, like Noack et al. (2003). Figure 3 shows that the first two SVD modes form a harmonic oscillator, but I am not entirely show what the data clustering dots are showing. 

11. In general, this paper would benefit from some more references.

**Comment by AndreWeiner** [comment]
Hi Alan,
here are my changes based on your suggestions.

> 1. The DaVis file format is mentioned in the abstract, but not defined in the remainder of the paper. It might be good to include this with the discussion in paragraph 1 of the Statement of need Section.

The following text was added to the first paragraph of the statement of need:

*On the experimental side, software packages like DaVis allow exporting particle image velocimetry (PIV) snapshots as CSV files. Reading CSV files can be a daunting task, too. A sequence of snapshots might be organized in one or multiple files. If the data are stored in a single file, the file must be read first and then the individual snapshots must be extracted following some initially unknown pattern. If the data are spread out over multiple files, the time might be encoded in the file name, but it could be also the case that the files are located in individual folders whose names encode the time. The latter structure is typical for OpenFOAM run time post-processing data. Moreover, different software packages will create different file headers, which may have to be parsed or sometimes ignored.*

> 2. Clarify in paragraph 1 what is meant by "to improve complex technical application". This is pretty vague. For instance, you could improve this by saying something like "to improve the control of industrial processes..."

The sentence in question was re-written as follows:

*Those data offer great opportunities to optimize industrial processes or to understand natural phenomena.*

> 3. Clarify in paragraph 1 why "gaining insights from the data is becoming increasingly challenging." Is this simply because of the size of the data? If so, you could combine this sentence with the next one, saying something like "As modern datasets continue to grow, post-processing pipelines will be increasingly important for synthesizing different data formats and facilitating complex data analysis."

That is a really good sentence, and I shamelessly copied it into the paper.

> 4. The sentence "When confronted with such ideas..." sounds awkward, I recommend changing it to something like "Often these obstacles require significant research time to be spent accessing, converting, ..."

Probably a very German English sentence. I changed it to:

*Often, significant research time is spent on accessing, converting, ...*

> 5. Third paragraph in the Statement of Need section: It would be good to define/give examples for "computing statistics, performing modal analysis, or building reduced-order models". It would be even better to add some references about these things.

The following examples and references were added:

*The same is true for computing the mean, the standard deviation, histograms, or quantiles. Modal analysis techniques, like dynamic mode decomposition (DMD)[@schmid2010; @kutz2016] and proper orthogonal decomposition (POD)[@brunton2019], are available via the subpackage `flowtorch.analysis`. The third subpackage, `flowtorch.rom`, enables adding reduced-order models (ROMs), like cluster-based network modeling (CNM)[@fernex2021], to the post-processing pipeline.*

> 6. I think Figure 1 could be improved in a few ways. For instance, it would be good if all the package dependencies were all the same color, to indicate they are the same type of thing. It might be nice to expand this figure, showing some of the sub-libraries like the DMD class, the FileReaders, etc. but this might be too much.

The colors of all dependencies were unified, and all significant dependencies were added.

> 7. Before the "DMD analysis of airfoil surface data" section, you say "Reduced-order-model (ROM)" but reduced order models have been introduced earlier in the document. It would be good to move the (ROM) abbreviation to the earliest use.

Done.

> 8. If there is a reference for the airfoil dataset, please add it.

The simulation is available on Github. I linked the repo in the article:

*The OpenFOAM configuration files to produce the dataset are available in a separate [GitHub repository](https://github.com/AndreWeiner/naca0012_shock_buffet).*

> 9. Figure 2:
(a) Please clarify if the images are in the (x, z) space, and m. 8, m. 6, etc. refer to modes 8, modes 6, and so on.
(b) Other than the shock front, is there some physical interpretations of the DMD modes or their characteristic frequencies (for instance, the top and bottom modes seem to be harmonics)?
(c) Please reduce the number of significant digits shown on the colorbars, and it might be good to use the same colorbar for all three modes.
(d) Maybe I missed it, but what is the significant of the "cp" in the title?

a) I've added y/c as axis label and defined *c* as the chord length; *modes* is not abbreviated anymore
b) I added the following info to the figure's caption: *Modes 8 and 18 are harmonics. The motion of the shock front is correlated with changes in the pressure values close to the trailing edge. This effect can be nicely observed via the mode animations in the [documentation](https://flowmodelingcontrol.github.io/flowtorch-docs/1.0/notebooks/dmd_naca0012_surface.html) and indicates the existence of a physical link between both effects.*
c) I normalized the plots to [0,1] and removed the colorbars; the fields are actually unit vectors, and the absolute values are not really important
d) I wrote *pressure coefficient* in the title instead of using an abbreviation.

> 10. In the first paragraph of "CNM of the flow past a circular cylinder" Section, it should be "always consultants of three steps". It would also be good to add some description and a reference on reduced order models of the cylinder flow, like Noack et al. (2003). Figure 3 shows that the first two SVD modes form a harmonic oscillator, but I am not entirely show what the data clustering dots are showing.

I added the reference to Noack's article. I also tried to clarify the caption a little bit:

*Phase-space representation of data clustering (large dots) and trajectory; the numbering reflects the sequence in which the centroids are visited; the smaller dots mark interpolated time steps between the centroids and are colored by their cluster affiliation (only for visualization).*

> In general, this paper would benefit from some more references.

I added 4 additional references. The books by Brunton and Kutz that I referenced contain very comprehensive lists of literature relevant for POD, DMD, and ROM (which is also why I chose them over other references).

Thanks again Alan. This was indeed a truly useful review process so far. Please, let me know if further changes are required.

Best, Andre
