### ISSUE TITLE
Can I install flowtorch on windows wsl(ubuntu 20.04)?

### ISSUE THREAD

**Issue by smallduan** [FlowModelingControl/flowtorch#36]
Hello

I want to use flowtorch on my windows systerm. I want to know if it can be installed by the wsl(I have tried to do it ,but I am failed).

**Comment by AndreWeiner** [comment]
Dear @smallduan,
I have yet to have the chance to test flowTorch on Windows. A few pieces of code are Linux/Unix specific (Dataloaders), but I plan to replace them. In the WSL/Ubuntu, everything should work as usual. Can you clarify why precisely the installation process fails?
Best regards,
Andre

**Comment by smallduan** [comment]
Dear @AndreWeiner 

Thank you for your help.

1. I installed flowtorch by `pip3 install git+https://github.com/FlowModelingControl/flowtorch`
3. I  fllowed the guide to install paraview

**Comment by smallduan** [comment]
Dear @AndreWeiner 

Thank you for your help.

1. I installed the flowtorch  use `pip3 install git+https://github.com/FlowModelingControl/flowtorch`.
2. I installed Paraview and changed the .bashrc
![step2](https://user-images.githubusercontent.com/52167150/227697633-6d036a75-2f7b-4e4b-82af-fb3580d4386d.png)
3. I use vscode to try the example from the online document in **Optimal hard threshold for singular values** with python3.8.10 
![step1](https://user-images.githubusercontent.com/52167150/227697687-11a340fc-1647-4873-b288-9ff407bdd672.png)

4. Then I get errors
![step3](https://user-images.githubusercontent.com/52167150/227697814-a8806b22-cdbc-46ce-97de-f14a26a94ef5.png)
![step4](https://user-images.githubusercontent.com/52167150/227697818-1c5501a3-cb06-4cf1-8c72-2ecffbfbc701.png)

Best regards 
smallduan

**Comment by AndreWeiner** [comment]
The problem comes from the ParaView Python module. ParaView comes with some versions of standard Python packages that sometimes conflict with the system's versions. I am still trying to figure out how to avoid this conflict in the installation procedure. Two solutions:
1) if you don't need the ParaView module (no Tecplot data):
  - uninstall flowTorch: `pip3 uninstall flowtorch`
  - install the dev branch `pip3 install git+https://github.com/FlowModelingControl/flowtorch.git@aweiner`
2) if you need the Tecplot loader:
  - go to the installation path, e.g. `cd /opt/ParaView-5.9.1-MPI-Linux-Python3.8-x86_64/lib/python3.8/site-packages`
  - remove conflicting packages manually: `sudo rm -r h5py matplotlib pandas mpl_toolkits numpy pandas scipy pygments`

Option 1) is definitely the better one. Hope this helps.
Best, Andre

**Comment by smallduan** [comment]
Dear @AndreWeiner 

I have tried the option1 
![230326](https://user-images.githubusercontent.com/52167150/227759200-e4e83814-60ea-45ad-bc34-63fc392b8274.jpg)

and restart the wsl, but the same errors still account when I try to use `from flowtorch.analysis import SVD`. Maybe this problem is caused by the WSL.

**Comment by smallduan** [comment]
Dear @AndreWeiner  

I am going to install anaconda in wsl and try again. I hope I can finish it successfully.😊

**Comment by smallduan** [comment]
Hello @AndreWeiner 

I have installed flowtorch successfully by conda environment by option1. I think the problem above may caused by the system python environment.   

Best regards
smallduan

**Comment by AndreWeiner** [comment]
Dear @smallduan,
thank you so much for reporting back on how exactly you made it work. That will be very helpful for me when creating instructions for a Windows setup at some point in the future. I'll close this issue for now.
Thanks again,
Andre
